### PR TITLE
chore!: adopt slog, drop go-kit/log

### PR DESCRIPTION
**Pull request by tjhop**
The bulk of this change set was automated by the following script which
is being used to aid in converting the various exporters/projects to use
slog:

https://gist.github.com/tjhop/49f96fb7ebbe55b12deee0b0312d8434

### CODE REVIEW

**Comment by tjhop** [comment]
cc: @SuperQ

**Review by SuperQ — APPROVED** [review]

**Comment by SuperQ** [comment]
The lint failure is related to the Go upgrade. I merged the latest repo sync PR so the next sync should bring it up-to-date enough to support Go 1.23.

**Comment by SuperQ** [comment]
A rebase should fix the lint issue.

**Comment by tjhop** [comment]
rebased :+1:

**Comment by SuperQ** [comment]
> SA1019: expfmt.FmtText is deprecated: Use expfmt.NewFormat(expfmt.TypeTextPlain) instead. (staticcheck)

Hmm

**Comment by tjhop** [comment]
Woops, I tested builds after the rebase, didn't test linting or I would've seen that. Should be better now :+1:

**Pull request merged**
