### PR TITLE
Implement JSON stats v1 parsing

### PR DESCRIPTION
**Pull request by dswarbrick**
This implements support for parsing the BIND statistics exposed under the /json/v1 endpoint.

It must be explicitly enabled with `--bind.stats-version=json`.

Fixes: #82

### CODE REVIEW

**Comment by dswarbrick** [comment]
@SuperQ PTAL

**Comment by SuperQ** [comment]
OMG, yes

**Comment by dswarbrick** [comment]
@SuperQ Any chance of merging this this week? I have some more commits in the pipeline which will conflict until this lands in master.

**Review by SuperQ — APPROVED** [review]
LGTM. I guess we can update `auto` to support this later.

**Comment by dswarbrick** [comment]
> LGTM. I guess we can update `auto` to support this later.

Yes, I plan to do that when I remove the XML v2 support.

**Comment by dswarbrick** [comment]
Whilst checking for any weird regressions, I did notice that there were some metrics absent when using the JSON stats channel. In all cases, they were (or would have been) zero values. It appears that the JSON stats channel omits zero-value counters in most cases.

Some examples where using the XML stats channel resulted in zero-value metrics:
```
bind_query_errors_total{error="Failure"} 0
bind_recursive_clients 0
bind_resolver_dnssec_validation_errors_total{view="_bind"} 0
bind_resolver_dnssec_validation_success_total{result="ValNegOk",view="_bind"} 0
bind_resolver_dnssec_validation_success_total{result="ValOk",view="_bind"} 0
bind_resolver_query_duration_seconds_bucket{view="_bind",le="0.01"} 0
...
bind_zone_transfer_failure_total 0
bind_zone_transfer_rejected_total 0
bind_zone_transfer_success_total 0
```
I can't say for sure what impact that will have on end users. We can't expose metrics for things that the JSON stats channel doesn't tell us about - unless we explicitly pre-init metrics via some intermediate structs / vars.

**Comment by SuperQ** [comment]
Yes, we may want to switch to pre-declared metric descriptors in order to make sure we expose the 0 value metrics.

**Pull request merged**
